(() => {
  'use strict';
  const page=document.documentElement.dataset.page;
  const defaults={channel:'',theme:'selene',font:'zen',bg:'glass',opacity:'78',textSize:'15',limit:'12',blur:'1'};
  const qs=new URLSearchParams(location.search);
  const settings=()=>Object.fromEntries(Object.keys(defaults).map(k=>[k,qs.get(k)??defaults[k]]));
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const color=n=>{let h=0;for(const c of String(n||'viewer'))h=(h*31+c.charCodeAt(0))%360;return `hsl(${h} 82% 77%)`;};
  const apply=s=>{const b=document.body;b.className=`${page==='view'?'widget':'app-shell'} theme-${s.theme} bg-${s.bg} font-${s.font}${s.blur==='1'?' use-blur':''}`;document.documentElement.style.setProperty('--bubble-opacity',Math.max(.25,Math.min(1,+s.opacity/100)));document.documentElement.style.setProperty('--text-size',`${+s.textSize||15}px`);};
  const session=async id=>{if(!id||location.protocol==='file:')return null;try{const r=await fetch(`/api/auth/session?widget=${encodeURIComponent(id)}`);return r.ok?r.json():null;}catch{return null;}};

  async function view(){
    const s=settings();apply(s);const chat=document.querySelector('#chat'),mt=document.querySelector('#message-template'),at=document.querySelector('#alert-template'),limit=Math.max(1,+s.limit||12);
    const trim=()=>{while(chat.children.length>limit){const x=chat.lastElementChild;x.classList.add('is-leaving');setTimeout(()=>x.remove(),320);if(chat.children.length<=limit+1)break;x.remove();}};
    const role=t=>{const b=t.badges||'';if(b.includes('broadcaster'))return['broadcaster','LIVE'];if(b.includes('moderator')||t.mod==='1')return['mod','MOD'];if(b.includes('vip'))return['vip','VIP'];if(b.includes('subscriber')||t.subscriber==='1')return['sub','SUB'];return['',''];};
    const msg=(name,text,tags={})=>{const f=mt.content.cloneNode(true),[kind,label]=role(tags),badge=f.querySelector('.role-badge'),user=f.querySelector('.chat-message__name');if(kind){badge.classList.add(`badge-${kind}`);badge.textContent=label;}user.textContent=name||'Viewer';user.style.setProperty('--user-color',tags.color||color(name));f.querySelector('.chat-message__bubble').textContent=text||'';chat.prepend(f);trim();};
    const alert=(type,label,name,amount='',note='')=>{const f=at.content.cloneNode(true);f.querySelector('.chat-alert__border').classList.add(`alert-${type}`);f.querySelector('.chat-alert__kind').textContent=label;f.querySelector('.chat-alert__line').innerHTML=`<span class="a-name">${esc(name||'Anonymous')}</span>${amount?` <span class="a-amount">${esc(amount)}</span>`:''}`;const n=f.querySelector('.chat-alert__note');n.textContent=note||'';if(!n.textContent)n.remove();chat.prepend(f);trim();};
    window.addEventListener('message',e=>{if(e.data?.source!=='prism-editor')return;({message:()=>msg('Mika','Great stream! Thanks for today.',{subscriber:'1',badges:'subscriber/1'}),sub:()=>alert('sub','NEW SUBSCRIBER','mikan_tea','','Welcome!'),cheer:()=>alert('cheer','CHEER','Kenta','500 Bits','Nice play!'),tip:()=>alert('tip','TIP','Rin','JPY 500','Good luck!')}[e.data.type]||(()=>{}))();});
    if(qs.has('preview')){document.body.classList.add('is-preview');document.querySelector('#preview-channel').textContent=`TWITCH #${s.channel||'your_channel'}`;msg('Mika','Great stream! Thanks for today.',{subscriber:'1',badges:'subscriber/1'});}
    const auth=await session(qs.get('widget'));const channel=String(s.channel||'').trim().toLowerCase();if(!auth||!channel||!window.tmi){if(!auth&&channel)console.warn('Twitch認証が必要です。設定画面でTwitchに接続してください。');return;}
    const c=new window.tmi.Client({connection:{secure:true,reconnect:true},identity:{username:auth.login,password:`oauth:${auth.accessToken}`},options:{skipMembership:true},channels:[channel]});
    c.on('message',(_,t,text,self)=>{if(!self)msg(t['display-name']||t.username,text,t);});c.on('cheer',(_,t,text)=>alert('cheer','CHEER',t['display-name']||t.username,`${t.bits||''} Bits`,text));c.on('subscription',(_,u,_m,n)=>alert('sub','NEW SUBSCRIBER',u,'',n));c.on('resub',(_,u,m,n)=>alert('sub','RESUBSCRIBED',u,m?`${m} months`:'',n));c.on('subgift',(_,u,_m,r)=>alert('gift','GIFT SUB',u,`for ${r}`));
    c.connect().catch(console.warn);
  }
  async function editor(){
    const form=document.querySelector('#widget-form'),frame=document.querySelector('#widget-preview'),out=document.querySelector('#obs-url'),toast=document.querySelector('#toast'),key='prism-widget-id';let widget=qs.get('widget')||localStorage.getItem(key)||'',auth=await session(widget);if(qs.get('widget')){localStorage.setItem(key,widget);history.replaceState({},'',location.pathname);}
    const values=()=>({...defaults,...Object.fromEntries(new FormData(form)),blur:form.elements.blur.checked?'1':'0'});const url=(preview=false)=>{const p=new URLSearchParams(values());if(widget)p.set('widget',widget);if(preview)p.set('preview','1');return `${new URL('view.html',location.href).href}?${p}`;};let timer;const update=()=>{const s=values();apply(s);out.value=url();clearTimeout(timer);timer=setTimeout(()=>frame.src=url(true),80);document.querySelector('#opacity-value').textContent=`${s.opacity}%`;};
    const authUi=()=>{const ok=!!auth;document.querySelector('#auth-title').textContent=ok?`Connected: ${auth.login}`:'Twitch not connected';document.querySelector('#auth-copy').textContent=ok?'Live chat, subscriptions, and Bits are enabled.':'Design and test events work without Twitch sign-in.';document.querySelector('#twitch-login').hidden=ok;document.querySelector('#twitch-disconnect').hidden=!ok;document.querySelector('#connection-status').textContent=ok?`Connected: #${auth.login}`:'Test mode';};
    [...form.elements].forEach(x=>{x.addEventListener('input',update);x.addEventListener('change',update);});document.querySelector('#copy-url').onclick=async()=>{await navigator.clipboard.writeText(out.value);toast.textContent='OBS URL copied';toast.classList.add('is-visible');setTimeout(()=>toast.classList.remove('is-visible'),1800);};document.querySelector('.test-controls').onclick=e=>{const t=e.target.dataset.test;if(t)frame.contentWindow?.postMessage({source:'prism-editor',type:t},location.protocol==='file:'?'*':location.origin);};document.querySelector('#twitch-login').onclick=()=>{if(location.protocol==='file:'){toast.textContent='Deploy to Vercel before Twitch sign-in';toast.classList.add('is-visible');return;}location.assign('/api/auth/login');};document.querySelector('#twitch-disconnect').onclick=async()=>{await fetch(`/api/auth/session?widget=${encodeURIComponent(widget)}`,{method:'DELETE'});localStorage.removeItem(key);widget='';auth=null;authUi();update();};authUi();update();
  }
  if(page==='view')view();if(page==='editor')editor();
})();
