(() => {
 const $=s=>document.querySelector(s),stage=$('.preview-stage');let zoom=false,imageData='',log=[];
 const notice=(selector,message)=>{$(selector).textContent=message;};
 const api=async(path,options={})=>{const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',...options.headers}});let j;try{j=await r.json();}catch{throw Error('APIが起動していません。本番環境の設定を確認してください。');}if(!r.ok)throw Error(j.error||'通信に失敗しました');return j;};
 const change=(el)=>el.dispatchEvent(new Event('input',{bubbles:true}));
 function fit(){const active=stage.querySelector('iframe:not([hidden])');if(!active)return;const w=stage.clientWidth,scale=zoom?1:w/1920;stage.classList.toggle('actual-size',zoom);stage.style.height=(zoom?540:w*1080/1920)+'px';Object.assign(active.style,{width:'1920px',height:'1080px',maxWidth:'none',maxHeight:'none',left:'0',top:'0',right:'auto',bottom:'auto',transformOrigin:'top left',transform:`scale(${scale})`});$('#preview-scale').textContent='· '+Math.round(scale*100)+'%';}
 new ResizeObserver(fit).observe(stage);window.addEventListener('panelchange',()=>requestAnimationFrame(fit));window.addEventListener('resize',()=>requestAnimationFrame(fit));
 $('#preview-fit').onclick=()=>{zoom=false;$('#preview-fit').setAttribute('aria-pressed','true');$('#preview-100').setAttribute('aria-pressed','false');fit();};
 $('#preview-100').onclick=()=>{zoom=true;$('#preview-fit').setAttribute('aria-pressed','false');$('#preview-100').setAttribute('aria-pressed','true');fit();};fit();
 const frameForm=$('#frame-form');
 $('#custom-frame-file').onchange=async e=>{try{
  const file=e.target.files[0];if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>1800000)throw Error('PNG / JPEG / WebP・1.8 MB以下の画像を選んでください。');
  const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);});
  const img=new Image();img.src=data;await img.decode();imageData=data;window.sparkleCustomFrame=data;frameForm.elements.customImage.value=data;change(frameForm.elements.customImage);
  notice('#custom-frame-status',`${img.naturalWidth} × ${img.naturalHeight} · プレビュー中・未保存。${img.naturalWidth!==1920||img.naturalHeight!==1080?'比率を保って1920×1080に収めます。':''}`);
 }catch(e){notice('#custom-frame-status',e.message);}};
 $('#save-custom-frame').onclick=async()=>{try{if(!imageData && frameForm.elements.customImage.value.startsWith('data:'))imageData=frameForm.elements.customImage.value;if(!imageData)throw Error('先に画像を選択してください。');notice('#custom-frame-status','画像を保存中…');const j=await api('/api/image',{method:'POST',body:JSON.stringify({data:imageData})});window.sparkleCustomFrame='/api/image?id='+j.id;frameForm.elements.customImage.value=window.sparkleCustomFrame;imageData='';change(frameForm.elements.customImage);notice('#custom-frame-status','保存しました。まとめURLにこの枠を含められます。');}catch(e){notice('#custom-frame-status',e.message);}};
 $('#remove-custom-frame').onclick=()=>{imageData='';window.sparkleCustomFrame='';frameForm.elements.customImage.value='';$('#custom-frame-file').value='';change(frameForm.elements.customImage);notice('#custom-frame-status','自作枠を外しました。');};
 for(const axis of ['x','y'])$('#custom-'+axis).value=frameForm.elements['custom'+axis.toUpperCase()].value;for(const axis of ['x','y'])$('#custom-'+axis).oninput=e=>{frameForm.elements['custom'+axis.toUpperCase()].value=e.target.value;change(frameForm.elements['custom'+axis.toUpperCase()]);};
 async function auth(){
  const box=$('#hype-auth');box.replaceChildren();const controls=document.createElement('div');controls.className='action-row';
  const connect=document.createElement('button');connect.type='button';connect.textContent='Twitchに接続';connect.className='apply-btn';connect.onclick=async()=>{location.href='/api/auth/login';};controls.append(connect);
  try{const j=await api('/api/auth/session');window.sparkleOverlay=j.overlay;const failures=j.subscriptions.filter(s=>!s.ok);notice('#connection-summary',j.error||`Twitch: ${j.login} · `+(failures.length?'購読エラー '+failures.map(x=>x.type+' ('+x.status+')').join(', '):'認証済み・イベント購読を受付'));connect.textContent='Twitchを再認証';
   for(const [label,method] of [['購読を再試行','POST'],['接続を解除','DELETE']]){const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=async()=>{try{await api('/api/auth/session',{method});if(method==='DELETE')window.sparkleOverlay='';await auth();}catch(e){notice('#connection-summary',e.message);}};controls.append(b);}
   window.dispatchEvent(new Event('sparkle-auth'));change($('#channel'));await loadLog();
  }catch(e){window.sparkleOverlay='';notice('#connection-summary','未接続 · '+e.message);}
  box.append(controls);const copy=controls.cloneNode(false);const open=document.createElement('button');open.textContent='アラートタブでTwitch接続を設定';open.onclick=()=>document.querySelector('[data-tab="alert"]').click();copy.append(open);$('#connection-summary').append(copy);
 }
 async function loadLog(){try{log=(await api('/api/events')).events;renderLog();}catch(e){notice('#event-log',e.message);}}
 function renderLog(){const filter=$('#log-filter').value,host=$('#event-log');host.replaceChildren();const rows=log.filter(e=>filter==='all'||e.type===filter||(filter==='sub'&&['resub','gift'].includes(e.type)));if(!rows.length){const p=document.createElement('p');p.className='empty-state';p.textContent='まだできごとはありません。通知を待っています。';host.append(p);return;}
  for(const e of rows){const item=document.createElement('article');item.className='log-row';const badge=document.createElement('span');badge.className='log-kind';badge.textContent=(e.test?'SAMPLE · ':'')+e.source.toUpperCase()+' / '+e.type.toUpperCase();const name=document.createElement('strong');name.textContent=e.name||'名前の提供なし';const time=document.createElement('time');time.textContent=e.time?new Date(e.time).toLocaleString('ja-JP'):'時刻の提供なし';const details=document.createElement('p');details.textContent=[e.amount!==null&&e.amount!==undefined?[e.amount,e.currency].filter(Boolean).join(' '):null,e.tier?'Tier '+e.tier:null,e.months!==null&&e.months!==undefined?e.months+'か月':null,e.count?e.count+'回':null,e.recipient?'贈り先 '+e.recipient:null,e.message].filter(Boolean).join(' · ');item.append(badge,name,time,details);host.append(item);}
 }
 $('#log-filter').onchange=renderLog;$('#refresh-log').onclick=loadLog;
 $('#export-log').onclick=()=>{const a=document.createElement('a'),u=URL.createObjectURL(new Blob([JSON.stringify(log,null,2)],{type:'application/json'}));a.href=u;a.download='sparkle-events.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};
 $('#streamlabs-mode').onchange=()=>{$('#sl-token-row').hidden=$('#streamlabs-mode').value!=='api';};
 $('#save-integrations').onclick=async()=>{try{const data={mode:$('#streamlabs-mode').value};for(const k of ['doneru','streamlabs'])if($('#'+k+'-url').value)data[k]=$('#'+k+'-url').value;if($('#streamlabs-token').value)data.streamlabsToken=$('#streamlabs-token').value;await api('/api/integrations',{method:'POST',body:JSON.stringify(data)});for(const sel of ['#doneru-url','#streamlabs-url','#streamlabs-token'])$(sel).value='';notice('#integration-status','設定を保存しました。まとめURLを発行し、公式管理画面の通知テストで表示を確認してください。');}catch(e){notice('#integration-status',e.message);}};
 const sample=async source=>{const event={id:crypto.randomUUID(),source,type:source==='twitch'?'streak':'donation',test:true,name:'Mika',userId:'demo-mika',count:12,amount:1000,currency:'JPY',message:'いつもありがとう！',time:new Date().toISOString()};if(source==='twitch'){delete event.amount;delete event.currency;delete event.message;}const payload={events:[event],stream:{live:true,streaks:{'demo-mika':{count:12}}}};
  for(const f of stage.querySelectorAll('iframe'))f.contentWindow?.postMessage({source:'sparkle-relay',payload},location.origin);
  if(source==='twitch')$('#widget-preview').contentWindow?.postMessage({source:'prism-editor',type:'streak-demo'},location.origin);
  log.unshift(event);renderLog();notice('#integration-status','サンプルをプレビューに送りました。実通知の受信成功を示すテストではありません。');};
 document.querySelectorAll('[data-integration-test]').forEach(b=>b.onclick=()=>sample(b.dataset.integrationTest));$('#test-streak').onclick=()=>sample('twitch');
 $('#end-stream').onclick=async()=>{try{await api('/api/events',{method:'POST',body:JSON.stringify({action:'end-stream'})});for(const f of stage.querySelectorAll('iframe'))f.contentWindow?.postMessage({source:'sparkle-relay',payload:{events:[],stream:{live:false,streaks:{}}}},location.origin);notice('#integration-status','この配信のバッジを解除しました。累計視聴回数は変更しません。');}catch(e){notice('#integration-status',e.message);}};
 auth();api('/api/integrations').then(j=>{$('#streamlabs-mode').value=j.mode;$('#streamlabs-mode').onchange();notice('#integration-status',`保存済み: Doneru ${j.doneru?'あり':'なし'} / Streamlabs ${j.streamlabs||j.streamlabsApi?'あり':'なし'}。Widget内の通知データはログに取得できません。`);}).catch(()=>{});setInterval(()=>{if(window.sparkleOverlay)loadLog();},15000);
})();
